import re

TEXT_ONLY = re.compile('[\W_]+')

GENRES = {
    "blues": ("Blues" , "https://www.discogs.com/genre/blues"),
    "brassmilitary": ("Brass & Military" , "https://www.discogs.com/genre/brass-military"),
    "childrens": ("Children's" , "https://www.discogs.com/genre/childrens"),
    "classical": ("Classical" , "https://www.discogs.com/genre/classical"),
    "electronic": ("Electronic" , "https://www.discogs.com/genre/electronic"),
    "folkworldcountry": ("Folk, World, & Country" , "https://www.discogs.com/genre/folk-world-country"),
    "funksoul": ("Funk / Soul" , "https://www.discogs.com/genre/funk-soul"),
    "hiphop": ("Hip-Hop" , "https://www.discogs.com/genre/hip-hop"),
    "jazz": ("Jazz" , "https://www.discogs.com/genre/jazz"),
    "latin": ("Latin" , "https://www.discogs.com/genre/latin"),
    "nonmusic": ("Non-Music" , "https://www.discogs.com/genre/non-music"),
    "pop": ("Pop" , "https://www.discogs.com/genre/pop"),
    "reggae": ("Reggae" , "https://www.discogs.com/genre/reggae"),
    "rock": ("Rock" , "https://www.discogs.com/genre/rock"),
    "stagescreen": ("Stage & Screen" , "https://www.discogs.com/genre/stage-screen")
}

STYLES = {'blues': {'boogiewoogie': ('Boogie Woogie',
                            'https://www.discogs.com/style/boogie+woogie'),
           'chicagoblues': ('Chicago Blues',
                            'https://www.discogs.com/style/chicago+blues'),
           'countryblues': ('Country Blues',
                            'https://www.discogs.com/style/country+blues'),
           'deltablues': ('Delta Blues',
                          'https://www.discogs.com/style/delta+blues'),
           'eastcoastblues': ('East Coast Blues',
                              'https://www.discogs.com/style/east+coast+blues'),
           'electricblues': ('Electric Blues',
                             'https://www.discogs.com/style/electric+blues'),
           'harmonicablues': ('Harmonica Blues',
                              'https://www.discogs.com/style/harmonica+blues'),
           'hillcountryblues': ('Hill Country Blues',
                                'https://www.discogs.com/style/hill+country+blues'),
           'jumpblues': ('Jump Blues',
                         'https://www.discogs.com/style/jump+blues'),
           'louisianablues': ('Louisiana Blues',
                              'https://www.discogs.com/style/louisiana+blues'),
           'memphisblues': ('Memphis Blues',
                            'https://www.discogs.com/style/memphis+blues'),
           'modernelectricblues': ('Modern Electric Blues',
                                   'https://www.discogs.com/style/modern+electric+blues'),
           'pianoblues': ('Piano Blues',
                          'https://www.discogs.com/style/piano+blues'),
           'piedmontblues': ('Piedmont Blues',
                             'https://www.discogs.com/style/piedmont+blues'),
           'texasblues': ('Texas Blues',
                          'https://www.discogs.com/style/texas+blues')},
 'brassmilitary': {'brassband': ('Brass Band',
                                 'https://www.discogs.com/style/brass+band'),
                   'educational': ('Educational',
                                   'https://www.discogs.com/style/educational'),
                   'marches': ('Marches',
                               'https://www.discogs.com/style/marches'),
                   'military': ('Military',
                                'https://www.discogs.com/style/military'),
                   'nurseryrhymes': ('Nursery Rhymes',
                                     'https://www.discogs.com/style/nursery+rhymes'),
                   'pipedrum': ('Pipe & Drum',
                                'https://www.discogs.com/style/pipe+&amp;+drum'),
                   'story': ('Story', 'https://www.discogs.com/style/story')},
 'classical': {'baroque': ('Baroque', 'https://www.discogs.com/style/baroque'),
               'choral': ('Choral', 'https://www.discogs.com/style/choral'),
               'classical': ('Classical',
                             'https://www.discogs.com/style/classical'),
               'contemporary': ('Contemporary',
                                'https://www.discogs.com/style/contemporary'),
               'early': ('Early', 'https://www.discogs.com/style/early'),
               'impressionist': ('Impressionist',
                                 'https://www.discogs.com/style/impressionist'),
               'medieval': ('Medieval',
                            'https://www.discogs.com/style/medieval'),
               'modern': ('Modern', 'https://www.discogs.com/style/modern'),
               'neoclassical': ('Neo-Classical',
                                'https://www.discogs.com/style/neo-classical'),
               'neoromantic': ('Neo-Romantic',
                               'https://www.discogs.com/style/neo-romantic'),
               'opera': ('Opera', 'https://www.discogs.com/style/opera'),
               'operetta': ('Operetta',
                            'https://www.discogs.com/style/operetta'),
               'oratorio': ('Oratorio',
                            'https://www.discogs.com/style/oratorio'),
               'postmodern': ('Post-Modern',
                              'https://www.discogs.com/style/post-modern'),
               'renaissance': ('Renaissance',
                               'https://www.discogs.com/style/renaissance'),
               'romantic': ('Romantic',
                            'https://www.discogs.com/style/romantic'),
               'serial': ('Serial', 'https://www.discogs.com/style/serial'),
               'twelvetone': ('Twelve-tone',
                              'https://www.discogs.com/style/twelve-tone'),
               'zarzuela': ('Zarzuela',
                            'https://www.discogs.com/style/zarzuela')},
 'electronic': {'abstract': ('Abstract',
                             'https://www.discogs.com/style/abstract'),
                'acid': ('Acid', 'https://www.discogs.com/style/acid'),
                'acidhouse': ('Acid House',
                              'https://www.discogs.com/style/acid+house'),
                'acidjazz': ('Acid Jazz',
                             'https://www.discogs.com/style/acid+jazz'),
                'ambient': ('Ambient', 'https://www.discogs.com/style/ambient'),
                'ballroom': ('Ballroom',
                             'https://www.discogs.com/style/ballroom'),
                'baltimoreclub': ('Baltimore Club',
                                  'https://www.discogs.com/style/baltimore+club'),
                'bassline': ('Bassline',
                             'https://www.discogs.com/style/bassline'),
                'beatdown': ('Beatdown',
                             'https://www.discogs.com/style/beatdown'),
                'berlinschool': ('Berlin-School',
                                 'https://www.discogs.com/style/berlin-school'),
                'bigbeat': ('Big Beat',
                            'https://www.discogs.com/style/big+beat'),
                'bleep': ('Bleep', 'https://www.discogs.com/style/bleep'),
                'breakbeat': ('Breakbeat',
                              'https://www.discogs.com/style/breakbeat'),
                'breakcore': ('Breakcore',
                              'https://www.discogs.com/style/breakcore'),
                'breaks': ('Breaks', 'https://www.discogs.com/style/breaks'),
                'brokenbeat': ('Broken Beat',
                               'https://www.discogs.com/style/broken+beat'),
                'chillwave': ('Chillwave',
                              'https://www.discogs.com/style/chillwave'),
                'chiptune': ('Chiptune',
                             'https://www.discogs.com/style/chiptune'),
                'dancepop': ('Dance-pop',
                             'https://www.discogs.com/style/dance-pop'),
                'darkambient': ('Dark Ambient',
                                'https://www.discogs.com/style/dark+ambient'),
                'darkwave': ('Darkwave',
                             'https://www.discogs.com/style/darkwave'),
                'deephouse': ('Deep House',
                              'https://www.discogs.com/style/deep+house'),
                'deeptechno': ('Deep Techno',
                               'https://www.discogs.com/style/deep+techno'),
                'disco': ('Disco', 'https://www.discogs.com/style/disco'),
                'discopolo': ('Disco Polo',
                              'https://www.discogs.com/style/disco+polo'),
                'donk': ('Donk', 'https://www.discogs.com/style/donk'),
                'doomcore': ('Doomcore',
                             'https://www.discogs.com/style/doomcore'),
                'downtempo': ('Downtempo',
                              'https://www.discogs.com/style/downtempo'),
                'drone': ('Drone', 'https://www.discogs.com/style/drone'),
                'drumnbass': ('Drum n Bass',
                              'https://www.discogs.com/style/drum+n+bass'),
                'dub': ('Dub', 'https://www.discogs.com/style/dub'),
                'dubstep': ('Dubstep', 'https://www.discogs.com/style/dubstep'),
                'dubtechno': ('Dub Techno',
                              'https://www.discogs.com/style/dub+techno'),
                'dungeonsynth': ('Dungeon Synth',
                                 'https://www.discogs.com/style/dungeon+synth'),
                'ebm': ('EBM', 'https://www.discogs.com/style/ebm'),
                'electro': ('Electro', 'https://www.discogs.com/style/electro'),
                'electroacoustic': ('Electroacoustic',
                                    'https://www.discogs.com/style/electroacoustic'),
                'electroclash': ('Electroclash',
                                 'https://www.discogs.com/style/electroclash'),
                'electrohouse': ('Electro House',
                                 'https://www.discogs.com/style/electro+house'),
                'electroswing': ('Electro Swing',
                                 'https://www.discogs.com/style/electro+swing'),
                'eurobeat': ('Eurobeat',
                             'https://www.discogs.com/style/eurobeat'),
                'eurodance': ('Eurodance',
                              'https://www.discogs.com/style/eurodance'),
                'eurodisco': ('Euro-Disco',
                              'https://www.discogs.com/style/euro-disco'),
                'eurohouse': ('Euro House',
                              'https://www.discogs.com/style/euro+house'),
                'experimental': ('Experimental',
                                 'https://www.discogs.com/style/experimental'),
                'footwork': ('Footwork',
                             'https://www.discogs.com/style/footwork'),
                'freestyle': ('Freestyle',
                              'https://www.discogs.com/style/freestyle'),
                'funkot': ('Funkot', 'https://www.discogs.com/style/funkot'),
                'futurejazz': ('Future Jazz',
                               'https://www.discogs.com/style/future+jazz'),
                'gabber': ('Gabber', 'https://www.discogs.com/style/gabber'),
                'garagehouse': ('Garage House',
                                'https://www.discogs.com/style/garage+house'),
                'ghetto': ('Ghetto', 'https://www.discogs.com/style/ghetto'),
                'ghettohouse': ('Ghetto House',
                                'https://www.discogs.com/style/ghetto+house'),
                'ghettotech': ('Ghettotech',
                               'https://www.discogs.com/style/ghettotech'),
                'glitch': ('Glitch', 'https://www.discogs.com/style/glitch'),
                'glitchhop': ('Glitch Hop',
                              'https://www.discogs.com/style/glitch+hop'),
                'goatrance': ('Goa Trance',
                              'https://www.discogs.com/style/goa+trance'),
                'grime': ('Grime', 'https://www.discogs.com/style/grime'),
                'halftime': ('Halftime',
                             'https://www.discogs.com/style/halftime'),
                'handsup': ('Hands Up',
                            'https://www.discogs.com/style/hands+up'),
                'happyhardcore': ('Happy Hardcore',
                                  'https://www.discogs.com/style/happy+hardcore'),
                'hardbeat': ('Hard Beat',
                             'https://www.discogs.com/style/hard+beat'),
                'hardcore': ('Hardcore',
                             'https://www.discogs.com/style/hardcore'),
                'hardhouse': ('Hard House',
                              'https://www.discogs.com/style/hard+house'),
                'hardstyle': ('Hardstyle',
                              'https://www.discogs.com/style/hardstyle'),
                'hardtechno': ('Hard Techno',
                               'https://www.discogs.com/style/hard+techno'),
                'hardtrance': ('Hard Trance',
                               'https://www.discogs.com/style/hard+trance'),
                'harshnoisewall': ('Harsh Noise Wall',
                                   'https://www.discogs.com/style/harsh+noise+wall'),
                'hinrg': ('Hi NRG', 'https://www.discogs.com/style/hi+nrg'),
                'hiphop': ('Hip Hop', 'https://www.discogs.com/style/hip+hop'),
                'hiphouse': ('Hip-House',
                             'https://www.discogs.com/style/hip-house'),
                'house': ('House', 'https://www.discogs.com/style/house'),
                'idm': ('IDM', 'https://www.discogs.com/style/idm'),
                'illbient': ('Illbient',
                             'https://www.discogs.com/style/illbient'),
                'industrial': ('Industrial',
                               'https://www.discogs.com/style/industrial'),
                'italodance': ('Italodance',
                               'https://www.discogs.com/style/italodance'),
                'italodisco': ('Italo-Disco',
                               'https://www.discogs.com/style/italo-disco'),
                'italohouse': ('Italo House',
                               'https://www.discogs.com/style/italo+house'),
                'jazzdance': ('Jazzdance',
                              'https://www.discogs.com/style/jazzdance'),
                'jcore': ('J-Core', 'https://www.discogs.com/style/j-core'),
                'jerseyclub': ('Jersey Club',
                               'https://www.discogs.com/style/jersey+club'),
                'juke': ('Juke', 'https://www.discogs.com/style/juke'),
                'jumpstyle': ('Jumpstyle',
                              'https://www.discogs.com/style/jumpstyle'),
                'jungle': ('Jungle', 'https://www.discogs.com/style/jungle'),
                'latin': ('Latin', 'https://www.discogs.com/style/latin'),
                'leftfield': ('Leftfield',
                              'https://www.discogs.com/style/leftfield'),
                'lentoviolento': ('Lento Violento',
                                  'https://www.discogs.com/style/lento+violento'),
                'makina': ('Makina', 'https://www.discogs.com/style/makina'),
                'minimal': ('Minimal', 'https://www.discogs.com/style/minimal'),
                'minimaltechno': ('Minimal Techno',
                                  'https://www.discogs.com/style/minimal+techno'),
                'modernclassical': ('Modern Classical',
                                    'https://www.discogs.com/style/modern+classical'),
                'moombahton': ('Moombahton',
                               'https://www.discogs.com/style/moombahton'),
                'musiqueconcrète': ('Musique Concrète',
                                    'https://www.discogs.com/style/musique+concrète'),
                'neofolk': ('Neofolk', 'https://www.discogs.com/style/neofolk'),
                'neotrance': ('Neo Trance',
                              'https://www.discogs.com/style/neo+trance'),
                'nerdcoretechno': ('Nerdcore Techno',
                                   'https://www.discogs.com/style/nerdcore+techno'),
                'newage': ('New Age', 'https://www.discogs.com/style/new+age'),
                'newbeat': ('New Beat',
                            'https://www.discogs.com/style/new+beat'),
                'noise': ('Noise', 'https://www.discogs.com/style/noise'),
                'nudisco': ('Nu-Disco',
                            'https://www.discogs.com/style/nu-disco'),
                'powerelectronics': ('Power Electronics',
                                     'https://www.discogs.com/style/power+electronics'),
                'progressivebreaks': ('Progressive Breaks',
                                      'https://www.discogs.com/style/progressive+breaks'),
                'progressivehouse': ('Progressive House',
                                     'https://www.discogs.com/style/progressive+house'),
                'progressivetrance': ('Progressive Trance',
                                      'https://www.discogs.com/style/progressive+trance'),
                'psytrance': ('Psy-Trance',
                              'https://www.discogs.com/style/psy-trance'),
                'rhythmicnoise': ('Rhythmic Noise',
                                  'https://www.discogs.com/style/rhythmic+noise'),
                'schranz': ('Schranz', 'https://www.discogs.com/style/schranz'),
                'skweee': ('Skweee', 'https://www.discogs.com/style/skweee'),
                'soundcollage': ('Sound Collage',
                                 'https://www.discogs.com/style/sound+collage'),
                'speedcore': ('Speedcore',
                              'https://www.discogs.com/style/speedcore'),
                'speedgarage': ('Speed Garage',
                                'https://www.discogs.com/style/speed+garage'),
                'synthpop': ('Synth-pop',
                             'https://www.discogs.com/style/synth-pop'),
                'synthwave': ('Synthwave',
                              'https://www.discogs.com/style/synthwave'),
                'techhouse': ('Tech House',
                              'https://www.discogs.com/style/tech+house'),
                'techno': ('Techno', 'https://www.discogs.com/style/techno'),
                'techtrance': ('Tech Trance',
                               'https://www.discogs.com/style/tech+trance'),
                'trance': ('Trance', 'https://www.discogs.com/style/trance'),
                'tribal': ('Tribal', 'https://www.discogs.com/style/tribal'),
                'tribalhouse': ('Tribal House',
                                'https://www.discogs.com/style/tribal+house'),
                'triphop': ('Trip Hop',
                            'https://www.discogs.com/style/trip+hop'),
                'tropicalhouse': ('Tropical House',
                                  'https://www.discogs.com/style/tropical+house'),
                'ukfunky': ('UK Funky',
                            'https://www.discogs.com/style/uk+funky'),
                'ukgarage': ('UK Garage',
                             'https://www.discogs.com/style/uk+garage'),
                'vaporwave': ('Vaporwave',
                              'https://www.discogs.com/style/vaporwave'),
                'witchhouse': ('Witch House',
                               'https://www.discogs.com/style/witch+house')},
 'folkworldcountry': {'aboriginal': ('Aboriginal',
                                     'https://www.discogs.com/style/aboriginal'),
                      'african': ('African',
                                  'https://www.discogs.com/style/african'),
                      'andalusianclassical': ('Andalusian Classical',
                                              'https://www.discogs.com/style/andalusian+classical'),
                      'andeanmusic': ('Andean Music',
                                      'https://www.discogs.com/style/andean+music'),
                      'appalachianmusic': ('Appalachian Music',
                                           'https://www.discogs.com/style/appalachian+music'),
                      'bangladeshiclassical': ('Bangladeshi Classical',
                                               'https://www.discogs.com/style/bangladeshi+classical'),
                      'basquemusic': ('Basque Music',
                                      'https://www.discogs.com/style/basque+music'),
                      'bengalimusic': ('Bengali Music',
                                       'https://www.discogs.com/style/bengali+music'),
                      'bhangra': ('Bhangra',
                                  'https://www.discogs.com/style/bhangra'),
                      'bluegrass': ('Bluegrass',
                                    'https://www.discogs.com/style/bluegrass'),
                      'cajun': ('Cajun', 'https://www.discogs.com/style/cajun'),
                      'cambodianclassical': ('Cambodian Classical',
                                             'https://www.discogs.com/style/cambodian+classical'),
                      'canzonenapoletana': ('Canzone Napoletana',
                                            'https://www.discogs.com/style/canzone+napoletana'),
                      'carnatic': ('Carnatic',
                                   'https://www.discogs.com/style/carnatic'),
                      'catalanmusic': ('Catalan Music',
                                       'https://www.discogs.com/style/catalan+music'),
                      'celtic': ('Celtic',
                                 'https://www.discogs.com/style/celtic'),
                      'chacarera': ('Chacarera',
                                    'https://www.discogs.com/style/chacarera'),
                      'chineseclassical': ('Chinese Classical',
                                           'https://www.discogs.com/style/chinese+classical'),
                      'chutney': ('Chutney',
                                  'https://www.discogs.com/style/chutney'),
                      'cobla': ('Cobla', 'https://www.discogs.com/style/cobla'),
                      'copla': ('Copla', 'https://www.discogs.com/style/copla'),
                      'country': ('Country',
                                  'https://www.discogs.com/style/country'),
                      'cretan': ('Cretan',
                                 'https://www.discogs.com/style/cretan'),
                      'dangdut': ('Dangdut',
                                  'https://www.discogs.com/style/dangdut'),
                      'fado': ('Fado', 'https://www.discogs.com/style/fado'),
                      'filk': ('Filk', 'https://www.discogs.com/style/filk'),
                      'flamenco': ('Flamenco',
                                   'https://www.discogs.com/style/flamenco'),
                      'folk': ('Folk', 'https://www.discogs.com/style/folk'),
                      'gagaku': ('Gagaku',
                                 'https://www.discogs.com/style/gagaku'),
                      'galiciantraditional': ('Galician Traditional',
                                              'https://www.discogs.com/style/galician+traditional'),
                      'gamelan': ('Gamelan',
                                  'https://www.discogs.com/style/gamelan'),
                      'ghazal': ('Ghazal',
                                 'https://www.discogs.com/style/ghazal'),
                      'griot': ('Griot', 'https://www.discogs.com/style/griot'),
                      'guarania': ('Guarania',
                                   'https://www.discogs.com/style/guarania'),
                      'gwoka': ('Gwo Ka',
                                'https://www.discogs.com/style/gwo+ka'),
                      'għana': ('Għana', 'https://www.discogs.com/style/għana'),
                      'hawaiian': ('Hawaiian',
                                   'https://www.discogs.com/style/hawaiian'),
                      'highlife': ('Highlife',
                                   'https://www.discogs.com/style/highlife'),
                      'hillbilly': ('Hillbilly',
                                    'https://www.discogs.com/style/hillbilly'),
                      'hindustani': ('Hindustani',
                                     'https://www.discogs.com/style/hindustani'),
                      'honkytonk': ('Honky Tonk',
                                    'https://www.discogs.com/style/honky+tonk'),
                      'huayno': ('Huayno',
                                 'https://www.discogs.com/style/huayno'),
                      'indianclassical': ('Indian Classical',
                                          'https://www.discogs.com/style/indian+classical'),
                      'jota': ('Jota', 'https://www.discogs.com/style/jota'),
                      'jugband': ('Jug Band',
                                  'https://www.discogs.com/style/jug+band'),
                      'kaseko': ('Kaseko',
                                 'https://www.discogs.com/style/kaseko'),
                      'keroncong': ('Keroncong',
                                    'https://www.discogs.com/style/keroncong'),
                      'kizomba': ('Kizomba',
                                  'https://www.discogs.com/style/kizomba'),
                      'klasik': ('Klasik',
                                 'https://www.discogs.com/style/klasik'),
                      'klezmer': ('Klezmer',
                                  'https://www.discogs.com/style/klezmer'),
                      'koreancourtmusic': ('Korean Court Music',
                                           'https://www.discogs.com/style/korean+court+music'),
                      'laomusic': ('Lao Music',
                                   'https://www.discogs.com/style/lao+music'),
                      'liscio': ('Liscio',
                                 'https://www.discogs.com/style/liscio'),
                      'lukkrung': ('Luk Krung',
                                   'https://www.discogs.com/style/luk+krung'),
                      'lukthung': ('Luk Thung',
                                   'https://www.discogs.com/style/luk+thung'),
                      'maloya': ('Maloya',
                                 'https://www.discogs.com/style/maloya'),
                      'mbalax': ('Mbalax',
                                 'https://www.discogs.com/style/mbalax'),
                      'mizrahi': ('Mizrahi',
                                  'https://www.discogs.com/style/mizrahi'),
                      'molam': ('Mo Lam',
                                'https://www.discogs.com/style/mo+lam'),
                      'morna': ('Morna', 'https://www.discogs.com/style/morna'),
                      'mouthmusic': ('Mouth Music',
                                     'https://www.discogs.com/style/mouth+music'),
                      'mugham': ('Mugham',
                                 'https://www.discogs.com/style/mugham'),
                      'nhạcvàng': ('Nhạc Vàng',
                                   'https://www.discogs.com/style/nhạc+vàng'),
                      'nordic': ('Nordic',
                                 'https://www.discogs.com/style/nordic'),
                      'népzene': ('Népzene',
                                  'https://www.discogs.com/style/népzene'),
                      'ottomanclassical': ('Ottoman Classical',
                                           'https://www.discogs.com/style/ottoman+classical'),
                      'overtonesinging': ('Overtone Singing',
                                          'https://www.discogs.com/style/overtone+singing'),
                      'pacific': ('Pacific',
                                  'https://www.discogs.com/style/pacific'),
                      'pasodoble': ('Pasodoble',
                                    'https://www.discogs.com/style/pasodoble'),
                      'persianclassical': ('Persian Classical',
                                           'https://www.discogs.com/style/persian+classical'),
                      'philippineclassical': ('Philippine Classical',
                                              'https://www.discogs.com/style/philippine+classical'),
                      'phlengphueachiwit': ('Phleng Phuea Chiwit',
                                            'https://www.discogs.com/style/phleng+phuea+chiwit'),
                      'piobaireachd': ('Piobaireachd',
                                       'https://www.discogs.com/style/piobaireachd'),
                      'polka': ('Polka', 'https://www.discogs.com/style/polka'),
                      'progressivebluegrass': ('Progressive Bluegrass',
                                               'https://www.discogs.com/style/progressive+bluegrass'),
                      'qawwali': ('Qawwali',
                                  'https://www.discogs.com/style/qawwali'),
                      'rebetiko': ('Rebetiko',
                                   'https://www.discogs.com/style/rebetiko'),
                      'romani': ('Romani',
                                 'https://www.discogs.com/style/romani'),
                      'runesinging': ('Rune Singing',
                                      'https://www.discogs.com/style/rune+singing'),
                      'salegy': ('Salegy',
                                 'https://www.discogs.com/style/salegy'),
                      'seashanties': ('Sea Shanties',
                                      'https://www.discogs.com/style/sea+shanties'),
                      'sephardic': ('Sephardic',
                                    'https://www.discogs.com/style/sephardic'),
                      'soukous': ('Soukous',
                                  'https://www.discogs.com/style/soukous'),
                      'sámimusic': ('Sámi Music',
                                    'https://www.discogs.com/style/sámi+music'),
                      'séga': ('Séga', 'https://www.discogs.com/style/séga'),
                      'taarab': ('Taarab',
                                 'https://www.discogs.com/style/taarab'),
                      'tamilfilmmusic': ('Tamil Film Music',
                                         'https://www.discogs.com/style/tamil+film+music'),
                      'thaiclassical': ('Thai Classical',
                                        'https://www.discogs.com/style/thai+classical'),
                      'volksmusik': ('Volksmusik',
                                     'https://www.discogs.com/style/volksmusik'),
                      'waiata': ('Waiata',
                                 'https://www.discogs.com/style/waiata'),
                      'westernswing': ('Western Swing',
                                       'https://www.discogs.com/style/western+swing'),
                      'yemenitejewish': ('Yemenite Jewish',
                                         'https://www.discogs.com/style/yemenite+jewish'),
                      'zamba': ('Zamba', 'https://www.discogs.com/style/zamba'),
                      'zemerivri': ('Zemer Ivri',
                                    'https://www.discogs.com/style/zemer+ivri'),
                      'zouk': ('Zouk', 'https://www.discogs.com/style/zouk'),
                      'zydeco': ('Zydeco',
                                 'https://www.discogs.com/style/zydeco'),
                      'éntekhno': ('Éntekhno',
                                   'https://www.discogs.com/style/éntekhno')},
 'funksoul': {'bayoufunk': ('Bayou Funk',
                            'https://www.discogs.com/style/bayou+funk'),
              'boogie': ('Boogie', 'https://www.discogs.com/style/boogie'),
              'contemporaryrb': ('Contemporary R&B',
                                 'https://www.discogs.com/style/contemporary+r&amp;b'),
              'freefunk': ('Free Funk',
                           'https://www.discogs.com/style/free+funk'),
              'funk': ('Funk', 'https://www.discogs.com/style/funk'),
              'gogo': ('Gogo', 'https://www.discogs.com/style/gogo'),
              'gospel': ('Gospel', 'https://www.discogs.com/style/gospel'),
              'minneapolissound': ('Minneapolis Sound',
                                   'https://www.discogs.com/style/minneapolis+sound'),
              'neosoul': ('Neo Soul', 'https://www.discogs.com/style/neo+soul'),
              'newjackswing': ('New Jack Swing',
                               'https://www.discogs.com/style/new+jack+swing'),
              'pfunk': ('P.Funk', 'https://www.discogs.com/style/p.funk'),
              'psychedelic': ('Psychedelic',
                              'https://www.discogs.com/style/psychedelic'),
              'rhythmblues': ('Rhythm & Blues',
                              'https://www.discogs.com/style/rhythm+&amp;+blues'),
              'soul': ('Soul', 'https://www.discogs.com/style/soul'),
              'swingbeat': ('Swingbeat',
                            'https://www.discogs.com/style/swingbeat'),
              'ukstreetsoul': ('UK Street Soul',
                               'https://www.discogs.com/style/uk+street+soul')},
 'hiphop': {'bassmusic': ('Bass Music',
                          'https://www.discogs.com/style/bass+music'),
            'beatbox': ('Beatbox', 'https://www.discogs.com/style/beatbox'),
            'bongoflava': ('Bongo Flava',
                           'https://www.discogs.com/style/bongo+flava'),
            'boombap': ('Boom Bap', 'https://www.discogs.com/style/boom+bap'),
            'bounce': ('Bounce', 'https://www.discogs.com/style/bounce'),
            'britcore': ('Britcore', 'https://www.discogs.com/style/britcore'),
            'cloudrap': ('Cloud Rap',
                         'https://www.discogs.com/style/cloud+rap'),
            'conscious': ('Conscious',
                          'https://www.discogs.com/style/conscious'),
            'crunk': ('Crunk', 'https://www.discogs.com/style/crunk'),
            'cutupdj': ('Cut-up/DJ', 'https://www.discogs.com/style/cut-up/dj'),
            'djbattletool': ('DJ Battle Tool',
                             'https://www.discogs.com/style/dj+battle+tool'),
            'favelafunk': ('Favela Funk',
                           'https://www.discogs.com/style/favela+funk'),
            'gangsta': ('Gangsta', 'https://www.discogs.com/style/gangsta'),
            'gfunk': ('G-Funk', 'https://www.discogs.com/style/g-funk'),
            'gogo': ('Go-Go', 'https://www.discogs.com/style/go-go'),
            'hardcorehiphop': ('Hardcore Hip-Hop',
                               'https://www.discogs.com/style/hardcore+hip-hop'),
            'hiplife': ('Hiplife', 'https://www.discogs.com/style/hiplife'),
            'horrorcore': ('Horrorcore',
                           'https://www.discogs.com/style/horrorcore'),
            'hyphy': ('Hyphy', 'https://www.discogs.com/style/hyphy'),
            'instrumental': ('Instrumental',
                             'https://www.discogs.com/style/instrumental'),
            'jazzyhiphop': ('Jazzy Hip-Hop',
                            'https://www.discogs.com/style/jazzy+hip-hop'),
            'kwaito': ('Kwaito', 'https://www.discogs.com/style/kwaito'),
            'miamibass': ('Miami Bass',
                          'https://www.discogs.com/style/miami+bass'),
            'motswako': ('Motswako', 'https://www.discogs.com/style/motswako'),
            'phonk': ('Phonk', 'https://www.discogs.com/style/phonk'),
            'poprap': ('Pop Rap', 'https://www.discogs.com/style/pop+rap'),
            'raggahiphop': ('Ragga HipHop',
                            'https://www.discogs.com/style/ragga+hiphop'),
            'rnbswing': ('RnB/Swing',
                         'https://www.discogs.com/style/rnb/swing'),
            'screw': ('Screw', 'https://www.discogs.com/style/screw'),
            'spaza': ('Spaza', 'https://www.discogs.com/style/spaza'),
            'thugrap': ('Thug Rap', 'https://www.discogs.com/style/thug+rap'),
            'trap': ('Trap', 'https://www.discogs.com/style/trap'),
            'turntablism': ('Turntablism',
                            'https://www.discogs.com/style/turntablism')},
 'jazz': {'afrobeat': ('Afrobeat', 'https://www.discogs.com/style/afrobeat'),
          'afrocubanjazz': ('Afro-Cuban Jazz',
                            'https://www.discogs.com/style/afro-cuban+jazz'),
          'avantgardejazz': ('Avant-garde Jazz',
                             'https://www.discogs.com/style/avant-garde+jazz'),
          'bigband': ('Big Band', 'https://www.discogs.com/style/big+band'),
          'bop': ('Bop', 'https://www.discogs.com/style/bop'),
          'bossanova': ('Bossa Nova',
                        'https://www.discogs.com/style/bossa+nova'),
          'capejazz': ('Cape Jazz', 'https://www.discogs.com/style/cape+jazz'),
          'contemporaryjazz': ('Contemporary Jazz',
                               'https://www.discogs.com/style/contemporary+jazz'),
          'cooljazz': ('Cool Jazz', 'https://www.discogs.com/style/cool+jazz'),
          'darkjazz': ('Dark Jazz', 'https://www.discogs.com/style/dark+jazz'),
          'dixieland': ('Dixieland', 'https://www.discogs.com/style/dixieland'),
          'easylistening': ('Easy Listening',
                            'https://www.discogs.com/style/easy+listening'),
          'freeimprovisation': ('Free Improvisation',
                                'https://www.discogs.com/style/free+improvisation'),
          'freejazz': ('Free Jazz', 'https://www.discogs.com/style/free+jazz'),
          'fusion': ('Fusion', 'https://www.discogs.com/style/fusion'),
          'gypsyjazz': ('Gypsy Jazz',
                        'https://www.discogs.com/style/gypsy+jazz'),
          'hardbop': ('Hard Bop', 'https://www.discogs.com/style/hard+bop'),
          'jazzfunk': ('Jazz-Funk', 'https://www.discogs.com/style/jazz-funk'),
          'jazzrock': ('Jazz-Rock', 'https://www.discogs.com/style/jazz-rock'),
          'latinjazz': ('Latin Jazz',
                        'https://www.discogs.com/style/latin+jazz'),
          'modal': ('Modal', 'https://www.discogs.com/style/modal'),
          'postbop': ('Post Bop', 'https://www.discogs.com/style/post+bop'),
          'ragtime': ('Ragtime', 'https://www.discogs.com/style/ragtime'),
          'smoothjazz': ('Smooth Jazz',
                         'https://www.discogs.com/style/smooth+jazz'),
          'souljazz': ('Soul-Jazz', 'https://www.discogs.com/style/soul-jazz'),
          'spaceage': ('Space-Age', 'https://www.discogs.com/style/space-age'),
          'stride': ('Stride', 'https://www.discogs.com/style/stride'),
          'swing': ('Swing', 'https://www.discogs.com/style/swing')},
 'latin': {'afrocuban': ('Afro-Cuban',
                         'https://www.discogs.com/style/afro-cuban'),
           'aguinaldo': ('Aguinaldo',
                         'https://www.discogs.com/style/aguinaldo'),
           'bachata': ('Bachata', 'https://www.discogs.com/style/bachata'),
           'baião': ('Baião', 'https://www.discogs.com/style/baião'),
           'bambuco': ('Bambuco', 'https://www.discogs.com/style/bambuco'),
           'batucada': ('Batucada', 'https://www.discogs.com/style/batucada'),
           'beguine': ('Beguine', 'https://www.discogs.com/style/beguine'),
           'bolero': ('Bolero', 'https://www.discogs.com/style/bolero'),
           'bomba': ('Bomba', 'https://www.discogs.com/style/bomba'),
           'boogaloo': ('Boogaloo', 'https://www.discogs.com/style/boogaloo'),
           'bossanova': ('Bossanova',
                         'https://www.discogs.com/style/bossanova'),
           'candombe': ('Candombe', 'https://www.discogs.com/style/candombe'),
           'chacha': ('Cha-Cha', 'https://www.discogs.com/style/cha-cha'),
           'champeta': ('Champeta', 'https://www.discogs.com/style/champeta'),
           'charanga': ('Charanga', 'https://www.discogs.com/style/charanga'),
           'choro': ('Choro', 'https://www.discogs.com/style/choro'),
           'compas': ('Compas', 'https://www.discogs.com/style/compas'),
           'conjunto': ('Conjunto', 'https://www.discogs.com/style/conjunto'),
           'corrido': ('Corrido', 'https://www.discogs.com/style/corrido'),
           'cuatro': ('Cuatro', 'https://www.discogs.com/style/cuatro'),
           'cubano': ('Cubano', 'https://www.discogs.com/style/cubano'),
           'cumbia': ('Cumbia', 'https://www.discogs.com/style/cumbia'),
           'danzon': ('Danzon', 'https://www.discogs.com/style/danzon'),
           'descarga': ('Descarga', 'https://www.discogs.com/style/descarga'),
           'gaita': ('Gaita', 'https://www.discogs.com/style/gaita'),
           'guajira': ('Guajira', 'https://www.discogs.com/style/guajira'),
           'guaracha': ('Guaracha', 'https://www.discogs.com/style/guaracha'),
           'jibaro': ('Jibaro', 'https://www.discogs.com/style/jibaro'),
           'joropo': ('Joropo', 'https://www.discogs.com/style/joropo'),
           'lambada': ('Lambada', 'https://www.discogs.com/style/lambada'),
           'mambo': ('Mambo', 'https://www.discogs.com/style/mambo'),
           'marchacarnavalesca': ('Marcha Carnavalesca',
                                  'https://www.discogs.com/style/marcha+carnavalesca'),
           'mariachi': ('Mariachi', 'https://www.discogs.com/style/mariachi'),
           'marimba': ('Marimba', 'https://www.discogs.com/style/marimba'),
           'merengue': ('Merengue', 'https://www.discogs.com/style/merengue'),
           'mpb': ('MPB', 'https://www.discogs.com/style/mpb'),
           'musette': ('Musette', 'https://www.discogs.com/style/musette'),
           'músicacriolla': ('Música Criolla',
                             'https://www.discogs.com/style/música+criolla'),
           'norteño': ('Norteño', 'https://www.discogs.com/style/norteño'),
           'nuevacancion': ('Nueva Cancion',
                            'https://www.discogs.com/style/nueva+cancion'),
           'nuevatrova': ('Nueva Trova',
                          'https://www.discogs.com/style/nueva+trova'),
           'occitan': ('Occitan', 'https://www.discogs.com/style/occitan'),
           'pachanga': ('Pachanga', 'https://www.discogs.com/style/pachanga'),
           'plena': ('Plena', 'https://www.discogs.com/style/plena'),
           'porro': ('Porro', 'https://www.discogs.com/style/porro'),
           'quechua': ('Quechua', 'https://www.discogs.com/style/quechua'),
           'ranchera': ('Ranchera', 'https://www.discogs.com/style/ranchera'),
           'reggaeton': ('Reggaeton',
                         'https://www.discogs.com/style/reggaeton'),
           'rumba': ('Rumba', 'https://www.discogs.com/style/rumba'),
           'salsa': ('Salsa', 'https://www.discogs.com/style/salsa'),
           'samba': ('Samba', 'https://www.discogs.com/style/samba'),
           'sambacanção': ('Samba-Canção',
                           'https://www.discogs.com/style/samba-canção'),
           'seresta': ('Seresta', 'https://www.discogs.com/style/seresta'),
           'son': ('Son', 'https://www.discogs.com/style/son'),
           'sonero': ('Sonero', 'https://www.discogs.com/style/sonero'),
           'sonmontuno': ('Son Montuno',
                          'https://www.discogs.com/style/son+montuno'),
           'tango': ('Tango', 'https://www.discogs.com/style/tango'),
           'tejano': ('Tejano', 'https://www.discogs.com/style/tejano'),
           'timba': ('Timba', 'https://www.discogs.com/style/timba'),
           'trova': ('Trova', 'https://www.discogs.com/style/trova'),
           'vallenato': ('Vallenato',
                         'https://www.discogs.com/style/vallenato')},
 'nonmusic': {'audiobook': ('Audiobook',
                            'https://www.discogs.com/style/audiobook'),
              'comedy': ('Comedy', 'https://www.discogs.com/style/comedy'),
              'dialogue': ('Dialogue',
                           'https://www.discogs.com/style/dialogue'),
              'education': ('Education',
                            'https://www.discogs.com/style/education'),
              'erotic': ('Erotic', 'https://www.discogs.com/style/erotic'),
              'fieldrecording': ('Field Recording',
                                 'https://www.discogs.com/style/field+recording'),
              'healthfitness': ('Health-Fitness',
                                'https://www.discogs.com/style/health-fitness'),
              'interview': ('Interview',
                            'https://www.discogs.com/style/interview'),
              'monolog': ('Monolog', 'https://www.discogs.com/style/monolog'),
              'movieeffects': ('Movie Effects',
                               'https://www.discogs.com/style/movie+effects'),
              'poetry': ('Poetry', 'https://www.discogs.com/style/poetry'),
              'political': ('Political',
                            'https://www.discogs.com/style/political'),
              'promotional': ('Promotional',
                              'https://www.discogs.com/style/promotional'),
              'publicbroadcast': ('Public Broadcast',
                                  'https://www.discogs.com/style/public+broadcast'),
              'publicserviceannouncement': ('Public Service Announcement',
                                            'https://www.discogs.com/style/public+service+announcement'),
              'radioplay': ('Radioplay',
                            'https://www.discogs.com/style/radioplay'),
              'religious': ('Religious',
                            'https://www.discogs.com/style/religious'),
              'sermon': ('Sermon', 'https://www.discogs.com/style/sermon'),
              'soundart': ('Sound Art',
                           'https://www.discogs.com/style/sound+art'),
              'soundpoetry': ('Sound Poetry',
                              'https://www.discogs.com/style/sound+poetry'),
              'specialeffects': ('Special Effects',
                                 'https://www.discogs.com/style/special+effects'),
              'speech': ('Speech', 'https://www.discogs.com/style/speech'),
              'spokenword': ('Spoken Word',
                             'https://www.discogs.com/style/spoken+word'),
              'technical': ('Technical',
                            'https://www.discogs.com/style/technical'),
              'therapy': ('Therapy', 'https://www.discogs.com/style/therapy')},
 'pop': {'ballad': ('Ballad', 'https://www.discogs.com/style/ballad'),
         'barbershop': ('Barbershop',
                        'https://www.discogs.com/style/barbershop'),
         'bollywood': ('Bollywood', 'https://www.discogs.com/style/bollywood'),
         'breakin': ('Break-In', 'https://www.discogs.com/style/break-in'),
         'bubblegum': ('Bubblegum', 'https://www.discogs.com/style/bubblegum'),
         'cantopop': ('Cantopop', 'https://www.discogs.com/style/cantopop'),
         'chanson': ('Chanson', 'https://www.discogs.com/style/chanson'),
         'citypop': ('City Pop', 'https://www.discogs.com/style/city+pop'),
         'enka': ('Enka', 'https://www.discogs.com/style/enka'),
         'ethnopop': ('Ethno-pop', 'https://www.discogs.com/style/ethno-pop'),
         'europop': ('Europop', 'https://www.discogs.com/style/europop'),
         'hokkienpop': ('Hokkien Pop',
                        'https://www.discogs.com/style/hokkien+pop'),
         'indiepop': ('Indie Pop', 'https://www.discogs.com/style/indie+pop'),
         'indopop': ('Indo-Pop', 'https://www.discogs.com/style/indo-pop'),
         'jpop': ('J-pop', 'https://www.discogs.com/style/j-pop'),
         'karaoke': ('Karaoke', 'https://www.discogs.com/style/karaoke'),
         'kayōkyoku': ('Kayōkyoku', 'https://www.discogs.com/style/kayōkyoku'),
         'kpop': ('K-pop', 'https://www.discogs.com/style/k-pop'),
         'levenslied': ('Levenslied',
                        'https://www.discogs.com/style/levenslied'),
         'lightmusic': ('Light Music',
                        'https://www.discogs.com/style/light+music'),
         'mandopop': ('Mandopop', 'https://www.discogs.com/style/mandopop'),
         'musichall': ('Music Hall',
                       'https://www.discogs.com/style/music+hall'),
         'novelty': ('Novelty', 'https://www.discogs.com/style/novelty'),
         'néokyma': ('Néo Kyma', 'https://www.discogs.com/style/néo+kyma'),
         'ryūkōka': ('Ryūkōka', 'https://www.discogs.com/style/ryūkōka'),
         'schlager': ('Schlager', 'https://www.discogs.com/style/schlager'),
         'villancicos': ('Villancicos',
                         'https://www.discogs.com/style/villancicos'),
         'vocal': ('Vocal', 'https://www.discogs.com/style/vocal')},
 'reggae': {'azonto': ('Azonto', 'https://www.discogs.com/style/azonto'),
            'bubbling': ('Bubbling', 'https://www.discogs.com/style/bubbling'),
            'calypso': ('Calypso', 'https://www.discogs.com/style/calypso'),
            'dancehall': ('Dancehall',
                          'https://www.discogs.com/style/dancehall'),
            'dubpoetry': ('Dub Poetry',
                          'https://www.discogs.com/style/dub+poetry'),
            'junkanoo': ('Junkanoo', 'https://www.discogs.com/style/junkanoo'),
            'loversrock': ('Lovers Rock',
                           'https://www.discogs.com/style/lovers+rock'),
            'mento': ('Mento', 'https://www.discogs.com/style/mento'),
            'ragga': ('Ragga', 'https://www.discogs.com/style/ragga'),
            'rapso': ('Rapso', 'https://www.discogs.com/style/rapso'),
            'reggae': ('Reggae', 'https://www.discogs.com/style/reggae'),
            'reggaegospel': ('Reggae Gospel',
                             'https://www.discogs.com/style/reggae+gospel'),
            'reggaepop': ('Reggae-Pop',
                          'https://www.discogs.com/style/reggae-pop'),
            'rocksteady': ('Rocksteady',
                           'https://www.discogs.com/style/rocksteady'),
            'rootsreggae': ('Roots Reggae',
                            'https://www.discogs.com/style/roots+reggae'),
            'soca': ('Soca', 'https://www.discogs.com/style/soca'),
            'steelband': ('Steel Band',
                          'https://www.discogs.com/style/steel+band')},
 'rock': {'acidrock': ('Acid Rock', 'https://www.discogs.com/style/acid+rock'),
          'acoustic': ('Acoustic', 'https://www.discogs.com/style/acoustic'),
          'alternativerock': ('Alternative Rock',
                              'https://www.discogs.com/style/alternative+rock'),
          'aor': ('AOR', 'https://www.discogs.com/style/aor'),
          'arenarock': ('Arena Rock',
                        'https://www.discogs.com/style/arena+rock'),
          'artrock': ('Art Rock', 'https://www.discogs.com/style/art+rock'),
          'atmosphericblackmetal': ('Atmospheric Black Metal',
                                    'https://www.discogs.com/style/atmospheric+black+metal'),
          'avantgarde': ('Avantgarde',
                         'https://www.discogs.com/style/avantgarde'),
          'beat': ('Beat', 'https://www.discogs.com/style/beat'),
          'blackmetal': ('Black Metal',
                         'https://www.discogs.com/style/black+metal'),
          'bluesrock': ('Blues Rock',
                        'https://www.discogs.com/style/blues+rock'),
          'britpop': ('Brit Pop', 'https://www.discogs.com/style/brit+pop'),
          'classicrock': ('Classic Rock',
                          'https://www.discogs.com/style/classic+rock'),
          'coldwave': ('Coldwave', 'https://www.discogs.com/style/coldwave'),
          'countryrock': ('Country Rock',
                          'https://www.discogs.com/style/country+rock'),
          'crust': ('Crust', 'https://www.discogs.com/style/crust'),
          'deathcore': ('Deathcore', 'https://www.discogs.com/style/deathcore'),
          'deathmetal': ('Death Metal',
                         'https://www.discogs.com/style/death+metal'),
          'deathrock': ('Deathrock', 'https://www.discogs.com/style/deathrock'),
          'depressiveblackmetal': ('Depressive Black Metal',
                                   'https://www.discogs.com/style/depressive+black+metal'),
          'doommetal': ('Doom Metal',
                        'https://www.discogs.com/style/doom+metal'),
          'doowop': ('Doo Wop', 'https://www.discogs.com/style/doo+wop'),
          'dreampop': ('Dream Pop', 'https://www.discogs.com/style/dream+pop'),
          'emo': ('Emo', 'https://www.discogs.com/style/emo'),
          'ethereal': ('Ethereal', 'https://www.discogs.com/style/ethereal'),
          'folkmetal': ('Folk Metal',
                        'https://www.discogs.com/style/folk+metal'),
          'folkrock': ('Folk Rock', 'https://www.discogs.com/style/folk+rock'),
          'funeraldoommetal': ('Funeral Doom Metal',
                               'https://www.discogs.com/style/funeral+doom+metal'),
          'funkmetal': ('Funk Metal',
                        'https://www.discogs.com/style/funk+metal'),
          'garagerock': ('Garage Rock',
                         'https://www.discogs.com/style/garage+rock'),
          'glam': ('Glam', 'https://www.discogs.com/style/glam'),
          'goregrind': ('Goregrind', 'https://www.discogs.com/style/goregrind'),
          'gothicmetal': ('Gothic Metal',
                          'https://www.discogs.com/style/gothic+metal'),
          'gothrock': ('Goth Rock', 'https://www.discogs.com/style/goth+rock'),
          'grindcore': ('Grindcore', 'https://www.discogs.com/style/grindcore'),
          'groovemetal': ('Groove Metal',
                          'https://www.discogs.com/style/groove+metal'),
          'grunge': ('Grunge', 'https://www.discogs.com/style/grunge'),
          'hardrock': ('Hard Rock', 'https://www.discogs.com/style/hard+rock'),
          'heavymetal': ('Heavy Metal',
                         'https://www.discogs.com/style/heavy+metal'),
          'horrorrock': ('Horror Rock',
                         'https://www.discogs.com/style/horror+rock'),
          'indierock': ('Indie Rock',
                        'https://www.discogs.com/style/indie+rock'),
          'industrialmetal': ('Industrial Metal',
                              'https://www.discogs.com/style/industrial+metal'),
          'janglepop': ('Jangle Pop',
                        'https://www.discogs.com/style/jangle+pop'),
          'jrock': ('J-Rock', 'https://www.discogs.com/style/j-rock'),
          'krautrock': ('Krautrock', 'https://www.discogs.com/style/krautrock'),
          'krock': ('K-Rock', 'https://www.discogs.com/style/k-rock'),
          'lofi': ('Lo-Fi', 'https://www.discogs.com/style/lo-fi'),
          'lounge': ('Lounge', 'https://www.discogs.com/style/lounge'),
          'mathrock': ('Math Rock', 'https://www.discogs.com/style/math+rock'),
          'melodicdeathmetal': ('Melodic Death Metal',
                                'https://www.discogs.com/style/melodic+death+metal'),
          'melodichardcore': ('Melodic Hardcore',
                              'https://www.discogs.com/style/melodic+hardcore'),
          'metalcore': ('Metalcore', 'https://www.discogs.com/style/metalcore'),
          'mod': ('Mod', 'https://www.discogs.com/style/mod'),
          'ndw': ('NDW', 'https://www.discogs.com/style/ndw'),
          'newwave': ('New Wave', 'https://www.discogs.com/style/new+wave'),
          'noisecore': ('Noisecore', 'https://www.discogs.com/style/noisecore'),
          'nowave': ('No Wave', 'https://www.discogs.com/style/no+wave'),
          'numetal': ('Nu Metal', 'https://www.discogs.com/style/nu+metal'),
          'oi': ('Oi', 'https://www.discogs.com/style/oi'),
          'parody': ('Parody', 'https://www.discogs.com/style/parody'),
          'poppunk': ('Pop Punk', 'https://www.discogs.com/style/pop+punk'),
          'poprock': ('Pop Rock', 'https://www.discogs.com/style/pop+rock'),
          'pornogrind': ('Pornogrind',
                         'https://www.discogs.com/style/pornogrind'),
          'posthardcore': ('Post-Hardcore',
                           'https://www.discogs.com/style/post-hardcore'),
          'postmetal': ('Post-Metal',
                        'https://www.discogs.com/style/post-metal'),
          'postpunk': ('Post-Punk', 'https://www.discogs.com/style/post-punk'),
          'postrock': ('Post Rock', 'https://www.discogs.com/style/post+rock'),
          'powermetal': ('Power Metal',
                         'https://www.discogs.com/style/power+metal'),
          'powerpop': ('Power Pop', 'https://www.discogs.com/style/power+pop'),
          'powerviolence': ('Power Violence',
                            'https://www.discogs.com/style/power+violence'),
          'progressivemetal': ('Progressive Metal',
                               'https://www.discogs.com/style/progressive+metal'),
          'progrock': ('Prog Rock', 'https://www.discogs.com/style/prog+rock'),
          'psychedelicrock': ('Psychedelic Rock',
                              'https://www.discogs.com/style/psychedelic+rock'),
          'psychobilly': ('Psychobilly',
                          'https://www.discogs.com/style/psychobilly'),
          'pubrock': ('Pub Rock', 'https://www.discogs.com/style/pub+rock'),
          'punk': ('Punk', 'https://www.discogs.com/style/punk'),
          'rockabilly': ('Rockabilly',
                         'https://www.discogs.com/style/rockabilly'),
          'rockopera': ('Rock Opera',
                        'https://www.discogs.com/style/rock+opera'),
          'rockroll': ('Rock & Roll',
                       'https://www.discogs.com/style/rock+&amp;+roll'),
          'shoegaze': ('Shoegaze', 'https://www.discogs.com/style/shoegaze'),
          'ska': ('Ska', 'https://www.discogs.com/style/ska'),
          'skiffle': ('Skiffle', 'https://www.discogs.com/style/skiffle'),
          'sludgemetal': ('Sludge Metal',
                          'https://www.discogs.com/style/sludge+metal'),
          'softrock': ('Soft Rock', 'https://www.discogs.com/style/soft+rock'),
          'southernrock': ('Southern Rock',
                           'https://www.discogs.com/style/southern+rock'),
          'spacerock': ('Space Rock',
                        'https://www.discogs.com/style/space+rock'),
          'speedmetal': ('Speed Metal',
                         'https://www.discogs.com/style/speed+metal'),
          'stonerrock': ('Stoner Rock',
                         'https://www.discogs.com/style/stoner+rock'),
          'surf': ('Surf', 'https://www.discogs.com/style/surf'),
          'swamppop': ('Swamp Pop', 'https://www.discogs.com/style/swamp+pop'),
          'symphonicmetal': ('Symphonic Metal',
                             'https://www.discogs.com/style/symphonic+metal'),
          'symphonicrock': ('Symphonic Rock',
                            'https://www.discogs.com/style/symphonic+rock'),
          'technicaldeathmetal': ('Technical Death Metal',
                                  'https://www.discogs.com/style/technical+death+metal'),
          'thrash': ('Thrash', 'https://www.discogs.com/style/thrash'),
          'twist': ('Twist', 'https://www.discogs.com/style/twist'),
          'vikingmetal': ('Viking Metal',
                          'https://www.discogs.com/style/viking+metal')},
 'stagescreen': {'cabaret': ('Cabaret',
                             'https://www.discogs.com/style/cabaret'),
                 'musical': ('Musical',
                             'https://www.discogs.com/style/musical'),
                 'score': ('Score', 'https://www.discogs.com/style/score'),
                 'soundtrack': ('Soundtrack',
                                'https://www.discogs.com/style/soundtrack'),
                 'theme': ('Theme', 'https://www.discogs.com/style/theme'),
                 'vaudeville': ('Vaudeville',
                                'https://www.discogs.com/style/vaudeville'),
                 'videogamemusic': ('Video Game Music',
                                    'https://www.discogs.com/style/video+game+music')}}

def genre_styles(genre_list, style_list):
    unmatched_genres = []
    matched_genres = []
    genre_results = []
    style_results = []
    for genre in genre_list:
        norm_genre = TEXT_ONLY.sub('', genre).lower()
        if (match := GENRES.get(norm_genre)):
            matched_genres += [norm_genre]
            genre_results += [match]
        else:
            unmatched_genres += [genre]
    unmatched_styles = set()
    for style in style_list + unmatched_genres:
        norm_style = TEXT_ONLY.sub('', style).lower()
        for genre in matched_genres:
            if (match := STYLES[genre].get(norm_style)):
                style_results += [match]
            else:
                unmatched_styles.add(style)
    return genre_results, style_results, unmatched_styles


if __name__ == '__main__':
    print(discogs_genre_styles(GENRES, []))
